version: '3.3'

services:
        mysql:
                container_name: mysql
                image: mysql:latest
                ports:
                        - 3306:3306
                volumes:
                        - ./mysql/config:/docker-entrypoint-initdb.d
                        - ./mysql/data:/var/lib/mysql-files
                environment:
                        - MYSQL_ROOT_PASSWORD=password
                        - MYSQL_USER=sodium
                        - MYSQL_PASSWORD=password

